### ISSUE TITLE
Translation of the documentation

### ISSUE THREAD

**Issue by ongolaboy** [NLnetLabs/rpki-doc#23]
Hi,
is there a way to provide translation of the documentation in other languages ?

**Comment by AlexanderBand** [comment]
Hi! Thanks for your interest in a translation. I haven't done any research into this yet, but according to the [readthedocs documentation](https://docs.readthedocs.io/en/stable/guides/manage-translations.html) it should be possible to achieve this with tools such as [Weblate](https://weblate.org/en/) or [Transifex](https://www.transifex.com/). 

If you want, I'm willing to set up a free Weblate account to get this started.

**Comment by ongolaboy** [comment]
ok for me :)

**Comment by AlexanderBand** [comment]
I tried but getting a framework set up for translations is more effort than I can spare at the moment.
