### ISSUE TITLE
Where can I get support for RPKI related questions?

### ISSUE THREAD

**Issue by zeki893** [NLnetLabs/rpki-doc#28]
I tried to search on how to get support for RPKI but couldn't find any place in the docs. Is there a forum where can I go to ask questions?

**Comment by maelmans** [comment]
Hi, it depends on the nature of the questions. Can you elaborate some more?

**Comment by AlexanderBand** [comment]
Perhaps the [RPKI Mailing list](https://lists.nlnetlabs.nl/mailman/listinfo/rpki) can be of help.
