### ISSUE TITLE
Multi-vendor support

### ISSUE THREAD

**Issue by zeki893** [NLnetLabs/rpki-doc#29]
We have a mix of Juniper MX, Cisco Cat and Brocade MLX. I can't find any documentation or in the FAQ on how to support multi-vendor setup. If we have a multi-vendor BGP network does every router need to be RPKI capable?

**Comment by AlexanderBand** [comment]
Perhaps @job can weigh in on this question.

**Comment by job** [comment]
NTT has a similar situation - some devices cannot support RPKI ROV because of technical caveats.

I recommend to enable RPKI on the routers where you can enable RPKI, and ask your EBGP peers to enable RPKI ROV on their outbound direction (towards you) and reject RPKI invalids on your behalf.

**Comment by maelmans** [comment]
Most vendors will have some documentation on their websites with regards to configuring their brands routers.
