### ISSUE TITLE
Changes to table in “Functional differences across RIRs” section

### ISSUE THREAD

**Issue by chufia** [NLnetLabs/rpki-doc#70]
Hello guys,

After reviewing the table in the “Functional differences across RIRs” section of the Implementation Models page and having conversations with the RPKI experts from the RIRs, I would like to suggest some updates to the values in that table:

* “Multi-user support” should be “Yes” for LACNIC
* “Two-factor authentication” should be “Yes” for LACNIC
* “Auto-renew ROAs” - Remove note of explicit opt-in feature for LACNIC (This is now by default with no option to opt out)
* “Match “route” objects with ROAs” should be “Yes” for LACNIC
* “Match “route” objects with ROAs” should be “No” for ARIN (They will soon support automatic route object creation upon ROA generation but that’s planned to be released on Nov 4th)
* API should be “Yes” for LACNIC and for APNIC (APNIC released the API last week)

Also, we believe the "Nonrepudiation" row could be removed as ARIN doesn't do this anymore and we believe it doesn't offer much value to show a row that will be "No" for all the RIRs, but we are happy to leave this up to you.

Please let me know if you have any comments or questions.

Thanks!

**Comment by AlexanderBand** [comment]
Thanks Sofia. I updated the table in commit [98f5db3](https://github.com/NLnetLabs/rpki-doc/commit/98f5db3bd1c4ffaaebdd2508c45dc61e0012fbf3). I need to make some other changes before rebuilding the public documentation on ReadtheDocs.
